Container_Boundary(c2,""){
Component(ShapeEndpoint, "ShapeEndpoint", "Kotlin", "",$sprite="GPU,scale=0.3")
Component(ShapeService, "ShapeService", "Kotlin", "",$sprite="GPU,scale=0.3")
Component(ShapeRepository, "ShapeRepository", "Kotlin", "",$sprite="GPU,scale=0.3")
Component(ShapeStorageProvider, "ShapeStorageProvider", "Kotlin", "",$sprite="GPU,scale=0.3")
Component(ShapeEventPublisher, "ShapeEventPublisher", "Kotlin", "",$sprite="GPU,scale=0.3")
}
Rel(ShapeEndpoint,ShapeService,"calls")
Rel(ShapeService,ShapeRepository,"calls")
Rel(ShapeService,ShapeStorageProvider,"calls")
Rel(ShapeStorageProvider,MongoClient,"calls")
Rel(ShapeService,ShapeEventPublisher,"calls")
Rel(ShapeEventPublisher,RabbitClient,"calls")
